### ISSUE TITLE
techRecord_updateType is in a wrong position in GETTRLTechnicalRecordV3Complete, PUTTRLTechnicalRecordV3Complete

### ISSUE THREAD

**Issue by shivangidas** [dvsa/cvs-type-definitions#26]
Also techRecord_hiddenInVta 

techRecord_updateType, techRecord_hiddenInVta should be a top-level field in the schema

**Comment by naathanbrown** [comment]
Think I have potentially fixed this whilst doing some other work, will attach to the PR when I raise it
