### ISSUE TITLE
Auth into service needs to be an object

### ISSUE THREAD

**Issue by naathanbrown** [dvsa/cvs-type-definitions#52]
It's not a string, it's a complex object and the type needs to become this.

**Comment by naathanbrown** [comment]
`    {
      name: 'techRecord_authIntoService_cocIssueDate',
      label: 'COC issue date',
      type: FormNodeTypes.CONTROL,
      viewType: FormNodeViewTypes.DATE,
      editType: FormNodeEditTypes.DATE,
      isoDate: false
    },
    {
      name: 'techRecord_authIntoService_dateReceived',
      label: 'Date received',
      type: FormNodeTypes.CONTROL,
      viewType: FormNodeViewTypes.DATE,
      editType: FormNodeEditTypes.DATE,
      isoDate: false
    },
    {
      name: 'techRecord_authIntoService_datePending',
      label: 'Date pending',
      type: FormNodeTypes.CONTROL,
      viewType: FormNodeViewTypes.DATE,
      editType: FormNodeEditTypes.DATE,
      isoDate: false
    },
    {
      name: 'techRecord_authIntoService_dateAuthorised',
      label: 'Date authorised',
      type: FormNodeTypes.CONTROL,
      viewType: FormNodeViewTypes.DATE,
      editType: FormNodeEditTypes.DATE,
      isoDate: false
    },
    {
      name: 'techRecord_authIntoService_dateRejected',
      label: 'Date rejected',
      type: FormNodeTypes.CONTROL,
      viewType: FormNodeViewTypes.DATE,
      editType: FormNodeEditTypes.DATE,
      isoDate: false
    }
  ]
};`

This is the shape within VTM. Should just be on trailers. Is not require

**Comment by gjulien-bjss** [comment]
Or, for the formatted version
```ts
[
  {
    name: "techRecord_authIntoService_cocIssueDate",
    label: "COC issue date",
    type: FormNodeTypes.CONTROL,
    viewType: FormNodeViewTypes.DATE,
    editType: FormNodeEditTypes.DATE,
    isoDate: false,
  },
  {
    name: "techRecord_authIntoService_dateReceived",
    label: "Date received",
    type: FormNodeTypes.CONTROL,
    viewType: FormNodeViewTypes.DATE,
    editType: FormNodeEditTypes.DATE,
    isoDate: false,
  },
  {
    name: "techRecord_authIntoService_datePending",
    label: "Date pending",
    type: FormNodeTypes.CONTROL,
    viewType: FormNodeViewTypes.DATE,
    editType: FormNodeEditTypes.DATE,
    isoDate: false,
  },
  {
    name: "techRecord_authIntoService_dateAuthorised",
    label: "Date authorised",
    type: FormNodeTypes.CONTROL,
    viewType: FormNodeViewTypes.DATE,
    editType: FormNodeEditTypes.DATE,
    isoDate: false,
  },
  {
    name: "techRecord_authIntoService_dateRejected",
    label: "Date rejected",
    type: FormNodeTypes.CONTROL,
    viewType: FormNodeViewTypes.DATE,
    editType: FormNodeEditTypes.DATE,
    isoDate: false,
  },
];


```
